add junit report for all

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -114,6 +114,12 @@ jobs:
         run: |
           gotestsum --format=standard-verbose --junitfile=/tmp/test-results/op-batcher.xml -- -parallel=8 -coverpkg=github.com/ethereum-optimism/optimism/... -coverprofile=coverage.out ./...
 
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '/tmp/test-results/op-batcher.xml'
+
   op-proposer-test:
     runs-on: ubuntu-latest
 
@@ -135,6 +141,12 @@ jobs:
         working-directory: op-proposer
         run: |
           gotestsum --format=standard-verbose --junitfile=/tmp/test-results/op-proposer.xml -- -parallel=8 -coverpkg=github.com/ethereum-optimism/optimism/... -coverprofile=coverage.out ./...
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '/tmp/test-results/op-proposer.xml'
 
   op-e2e-http-test:
     runs-on: ubuntu-latest
@@ -160,6 +172,12 @@ jobs:
             --format=standard-verbose --junitfile=/tmp/test-results/op-e2e_http_true.xml \
             -- -timeout=20m -parallel=8 ./...
 
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '/tmp/test-results/op-e2e_http_true.xml'
+
   op-e2e-ws-test:
     runs-on: ubuntu-latest
 
@@ -183,3 +201,9 @@ jobs:
           OP_TESTLOG_DISABLE_COLOR=true OP_E2E_DISABLE_PARALLEL=false OP_E2E_USE_HTTP=false  gotestsum \
             --format=standard-verbose --junitfile=/tmp/test-results/op-e2e_http_false.xml \
             -- -timeout=20m -parallel=8 ./...
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '/tmp/test-results/op-e2e_http_false.xml'
